valorA = int(input())
valorB = int(input())
print(f"soma = {valorA + valorB}")
print(f"subtração = {valorA - valorB}")
print(f"multiplicação = {valorA * valorB}")
print(f"divisão = {valorA / valorB}")
